# ====== BUILD ======
FROM golang:1.24-alpine AS build
RUN apk add --no-cache git ca-certificates
WORKDIR /app
ENV CGO_ENABLED=0 GOPROXY=https://proxy.golang.org,direct
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -trimpath -ldflags="-s -w" -o /server ./cmd/api

# ====== RUNTIME ======
FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /server /server
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/server"]
