FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server ./src

FROM alpine:3.19
WORKDIR /root/
COPY --from=build /app/server ./server
EXPOSE 8080
CMD ["./server"]
