apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
  namespace: banking
  labels:
    app: banking-api
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
        component: backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: banking-api
        image: banking-api:latest
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: RATE_LIMIT_REQUESTS_PER_MINUTE
          value: "2000"
        livenessProbe:
          httpGet:
            path: /prometheus
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /prometheus
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: banking-api-service
  namespace: banking
  labels:
    app: banking-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: banking-api