---
- name: Deploy Core Banking Lab to k3s
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    k3s_version: "v1.31.5+k3s1"
    app_dir: "/opt/banking-app"
    docker_registry: "ghcr.io"  # Change to your registry
    image_tag: "{{ ansible_date_time.epoch }}"
    
  tasks:
    - name: Wait for instance to be ready
      wait_for_connection:
        timeout: 300

    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --disable servicelb
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      wait_for:
        port: 6443
        host: localhost
        timeout: 120

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig to ubuntu user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: yes

    - name: Install Python pip and kubernetes library
      apt:
        name: 
          - python3-pip
        state: present
        update_cache: yes

    - name: Install kubernetes Python library
      pip:
        name: kubernetes
        state: present

    - name: Install Helm
      shell: |
        curl https://get.helm.sh/helm-v3.12.0-linux-arm64.tar.gz | tar -xzO linux-arm64/helm > /usr/local/bin/helm
        chmod +x /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Copy Kubernetes manifests
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/{{ item | basename }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      with_fileglob:
        - "../../../k8s/*.yaml"

    - name: Create namespace first
      kubernetes.core.k8s:
        state: present
        src: "{{ app_dir }}/00-namespace.yaml"
        kubeconfig: /home/ubuntu/.kube/config
      become_user: ubuntu

    - name: Create image pull secret for GHCR
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ghcr-secret
            namespace: core-banking
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ ('{ \"auths\": { \"ghcr.io\": { \"auth\": \"' + (github_actor + ':' + github_token) | b64encode + '\" } } }') | b64encode }}"
        kubeconfig: /home/ubuntu/.kube/config
      vars:
        github_actor: "{{ github_actor }}"
        github_token: "{{ github_token }}"
      become_user: ubuntu

    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ app_dir }}/{{ item }}"
        kubeconfig: /home/ubuntu/.kube/config
      with_items:
        - "00-namespace.yaml"
        - "01-api-deployment.yaml"
        - "02-dashboard-deployment.yaml"
        - "03-monitoring-deployment.yaml"
        - "04-grafana-dashboards.yaml"
        - "05-kube-state-metrics.yaml"
      become_user: ubuntu

    - name: Wait for pods to be ready
      shell: |
        export KUBECONFIG=/home/ubuntu/.kube/config
        echo "Waiting for pods to be ready..."
        
        # Wait up to 10 minutes for pods to be running
        for i in {1..120}; do
          RUNNING_PODS=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | grep "Running" | wc -l || echo "0")
          TOTAL_PODS=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | wc -l || echo "0")
          FAILED_PODS=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | grep -E "Error|Failed|ImagePullBackOff|CrashLoopBackOff" | wc -l || echo "0")
          
          echo "Attempt $i/120: $RUNNING_PODS/$TOTAL_PODS pods running, $FAILED_PODS failed"
          
          # Check if we have any critical failures
          if [ "$FAILED_PODS" -gt 0 ]; then
            echo "Pods with issues detected:"
            kubectl get pods -n core-banking | grep -E "Error|Failed|ImagePullBackOff|CrashLoopBackOff" || true
            echo "Checking pod details for first failed pod..."
            FAILED_POD=$(kubectl get pods -n core-banking --no-headers | grep -E "Error|Failed|ImagePullBackOff|CrashLoopBackOff" | head -1 | awk '{print $1}')
            if [ ! -z "$FAILED_POD" ]; then
              echo "Events for $FAILED_POD:"
              kubectl describe pod "$FAILED_POD" -n core-banking | tail -10
            fi
          fi
          
          # Success criteria: at least monitoring stack (prometheus + kube-state-metrics) running
          PROMETHEUS_RUNNING=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | grep prometheus | grep "Running" | wc -l || echo "0")
          KSM_RUNNING=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | grep kube-state-metrics | grep "Running" | wc -l || echo "0")
          
          if [ "$PROMETHEUS_RUNNING" -gt 0 ] && [ "$KSM_RUNNING" -gt 0 ]; then
            echo "Core monitoring stack is running!"
            kubectl get pods -n core-banking
            
            # Check if banking apps are running too
            BANKING_RUNNING=$(kubectl get pods -n core-banking --no-headers 2>/dev/null | grep -E "banking-api|banking-dashboard" | grep "Running" | wc -l || echo "0")
            if [ "$BANKING_RUNNING" -gt 0 ]; then
              echo "Banking applications are also running - deployment fully successful!"
            else
              echo "Note: Banking applications may have image issues, but monitoring stack is operational"
            fi
            break
          fi
          
          if [ $i -eq 120 ]; then
            echo "Timeout waiting for core monitoring stack. Final status:"
            kubectl get pods -n core-banking
            echo "Deployment failed - core monitoring components not ready"
            exit 1
          fi
          
          sleep 5
        done
      become_user: ubuntu

    - name: Get application status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: core-banking
        kubeconfig: /home/ubuntu/.kube/config
      register: services
      become_user: ubuntu

    - name: Display application URLs
      debug:
        msg: |
          Banking API: http://{{ ansible_host }}:30080
          Dashboard: http://{{ ansible_host }}:30000
          Prometheus: http://{{ ansible_host }}:30090
          Grafana: http://{{ ansible_host }}:30030